### ISSUE TITLE
Swipe up into the drawer

### ISSUE THREAD

**Issue by TobiTenno** [jkuester/unlauncher#1]
It'd be smoother to swipe up directly into the app drawer, then pin your "favorites" at the top.

**Comment by jkuester** [comment]
To clarify, I think the approach I would like to take here is to keep the 2-pane home screen.  However, instead of having the "Apps" button, just be able to access the whole app drawer by swiping up again from the second pane.

**Comment by jkuester** [comment]
So, as it turns out, things get pretty tricky when trying to do more than 2 scenes with the MotionLayout (especially if you want to access all of them via a serious of "swipe up" actions).  I have spent a considerable amount of time tinkering with this and have not been able to get the UX to work in any sort of satisfactory way for swiping up again from the second pane to access the app drawer.

If I eliminate the original second pane altogether and replace it with the app drawer then everything works smoothly and I can swipe into and out of the app drawer very nicely.  While this was not my original goal, I am pretty happy with the look and feel of swiping directly to the app drawer.  (@TobiTenno and I worked together on some of the UX here and we did increase the max number of apps on the first pane to be 6 instead of 4 since we would be loosing the other 4 pinned apps from the second pane.  Additionally we moved the original "Options" button on the second pane to be a cog icon on the first pane).  

We are pretty happy with how things are looking, but I wanted to drop a comment out here and see if anyone else had thoughts/feedback. Below is a recording of the prototype interface. Thanks!

![unlauncher](https://user-images.githubusercontent.com/8441903/104462760-95a43280-5576-11eb-8987-114cb98d36fe.gif)
