### ISSUE TITLE
Unlauncher beta on android 6.0.1 crashes

### ISSUE THREAD

**Issue by ktnlikeasmallcat** [jkuester/unlauncher#129]
After updating from 1.3.0, both the beta releases quit unexpectedly upon returning home, and can't be called up, even after rebooting. Downgrading back to v 1.3 requires uninstalling first through F-droid.
Is there something I can do to get useful logs i can contribute from this crash? 
Is marshmallow intended to be supported in v2? 

More Info: The phone isn't rooted or anything, It's a ZTE Z833, a cheap old phone I'd like to keep the latest features from of this launcher on - is all, and I figure others may want the same.
1.3.0 works absolutely fine as is. Thanks for your time and work.

**Comment by jkuester** [comment]
Sorry for the late response here :sweat:. I have been able to successfully recreate this issue on Android 6.  It seems to happen only when upgrading from a previous version of Unlauncher when one or more of the Quick Buttons has been hidden. Still investigating the proper fix....

**Comment by jkuester** [comment]
Looks like this affects any Android version and is not specific to Android 6.  If you clear the storage before upgrading, the problem does not persist.

**Comment by jkuester** [comment]
The root cause of the issue is a mistake that I made with how the quick buttons preference value is stored.  I was storing the _Resource Id_ for the currently displayed icon in the datastore.  I have now learned that Android resource IDs [are not consistent between app versions](https://stackoverflow.com/questions/23124049/android-does-r-resource-id-changes-in-runtime).  The good news is this is a pretty easy fix, now that I know what is causing the crash.  The bad news is that there is no way to recover the quick button stored preferences for anyone running `1.3.0`.  The app will automatically reset those preferences when upgrading to `2.0.0`.  However, now it should not crash and subsequent upgrades in the future should not reset the preference.
