### ISSUE TITLE
Advice on syncing core fucntionality while keeping projects flexible in their differences

### ISSUE THREAD

**Issue by sduduzog** [jkuester/unlauncher#29]
There has been a number of changes that came in this year to the slim launcher project, not from me mostly but from people contributing. I worry that forks of slim launcher might suffer from upstream changes differing too much from the forks.

Is there a way we could minimize this? I don't know, like modularizing most stuff that's common and separating it into layers, or even have a common separate library like module, I don't know. 

I've received great feedback from people not only using slim launcher but also unlauncher too and it's really exciting

**Comment by sduduzog** [comment]
What I'll actively do is to go through issues in this repo and try, see which are close to plans I have for my project... I also want to be able to make super drastic changes with little impact to project that forked my repo

**Comment by jkuester** [comment]
👍 Thanks for the consideration of the Slim-Launcher forks!  

Speaking for Unlauncher, I can say that my process has been to try and use git to minimize the effort of keeping the forked code up-to-date with Slim-Launcher.   I usually wait for a new tag of Slim-Launcher to be cut, then I squash all of the changes in Slim-Launcher since the last tag down into a single commit.  Then I cherry-pick that commit over onto my Unlauncher branch. This is the point where I might have to resolve some merge conflicts if things changed in code that has diverged on Unlauncher, but usually it is not a big deal.  Git does all the heavy-lifting and so far I have not had any problems taking the latest changes from Slim-Launcher!

My main piece of advice would be to prioritize your vision for Slim-Launcher. Sure, listening to the community and having consideration for the extra users/contributors that forks like Unlauncher can bring in is great.  But, don't let that bog you down with over-architecting things or make you hesitant to do large-scale refactoring/uplifts. Close forks like Unlauncher should be able to incorporate these changes without much trouble (and honestly any improvements to the Slim-Launcher code base are improvements to Unlauncher and are most welcome)!

**Comment by jkuester** [comment]
On a practical note, one of the things you could do to make it easier to keep the forks up-to-date with Slim-Launcher would be to consider squashing the commits from PRs when merging them to `master`.  (So if you are using the GitHub web interface to merge PR's that would mean using the "Squash and Merge" button instead of "Create a merge commit" or "Rebase and merge").  The reason why I am currently squashing the changes from Slim-Launcher before pulling them into Unlauncher is because otherwise it is pretty messy to try and pull in a bunch of commits including various merge-commits.  Having just one normal commit in `master` that contains the changes from each PR would make it easier to cherry-pick the exact changes that we need. (And then I would also not loose all of the commit history from the changes by squashing.)
