### ISSUE TITLE
launcher month appears incorrectly

### ISSUE THREAD

**Issue by goldfrank** [jkuester/unlauncher#33]
On the launcher, under the time the month appears as "M01" rather than "January," i.e. "Thu M01 14.
![Screenshot_20210114-064553](https://user-images.githubusercontent.com/36973691/104587146-7ff54280-5634-11eb-966a-f46ac3263923.png)
"

**Comment by jkuester** [comment]
This is very strange.  The code to set the date value is here: https://github.com/jkuester/unlauncher/blob/912e48f6785367a55a607d57e6ff06b3f5986334/app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt#L139 and after perusing it for a bit I have not been able to think of any way that this should happen.  
AFIK `SimpleDateFormat("EEE, MMM dd", Locale.ROOT)` should always return the same value for everyone (regardless of the configuration on the local device.  (And I can confirm that the date says "Jan" on all of the devices I have tested...)

If you would not mind, could you share the version of Android you are running?  Also, could you include the default language you have set in your Android system settings?  These might be useful when trying to recreate this issue.

**Comment by goldfrank** [comment]
It's very strange indeed. I'm running Android 11 on a Google Pixel 4a, with language set to English (United States). Thanks for looking into this Please let me know if there are any other debugging steps I could take. I switched the language to English (UK) and there was no change.

**Comment by dalaeance** [comment]
I'm having the same problem on my P2XL running Android 11 (CalyxOS). My default language is English (Canada).
![IMG_20210118_151634](https://user-images.githubusercontent.com/30301418/104968276-65fc8c80-59b3-11eb-9a7d-0b94045d0ec4.jpg)

**Comment by jkuester** [comment]
Okay, so it appears something changed between Android 10 (API level 29) and Android 11 (API level 30) pertaining to how the SimpleDateFormate works with the ROOT locale and this is causing the issue. I have not been able to identify a particular changelog that explains the change, but I have seen date formatting masks change for particular locales in the past, so I expect something similar is going on here.  

Regardless, it seems more appropriate for Unlauncher to be pulling the device's locale to use for displaying the date/time instead of hard-coding ROOT.  With that change in place, I get the correct date display even when running Android 11.
