### ISSUE TITLE
[Request] Close keyboard after launching an app 

### ISSUE THREAD

**Issue by edaigle** [jkuester/unlauncher#38]
Thanks so much for this launcher, it's terrific :)

I've noticed that when we swipe down to bring up the app list, the cursor is activated in the "search apps" field - the keyboard doesn't appear yet, though. However if we then launch an app from the list, the keyboard is shown when we return to the launcher (via home button or clicking the power button and logging back in), and we have to press the back/down button to dismiss it. 

Personally I find this mildly confusing/annoying - would it make sense to either not activate the "search apps" field unless we tap it, or to dismiss the keyboard when we launch an app, to stop it coming up on return to the homescreen?

I'm very new to Android dev but I wouldn't mind giving this a try myself if others agree the change makes sense.

**Comment by jkuester** [comment]
Yes, you are right.  There are definitely some issues with that search box behavior.  I agree with you that it makes sense to not activate the "search apps" field unless you tap it. 

So, when an app is launched from the drawer, the search box should be reset and the next time the drawer is opened the search box should not be activated and the keyboard should stay closed until you tap on the search box again.  

I would absolutely be happy to accept a pull request for fixing these changes if you are interested!  (Otherwise I will work on addressing this when I get around to it).
