### ISSUE TITLE
Directly activate keyboard in searchfield when opening app list

### ISSUE THREAD

**Issue by egyfeny** [jkuester/unlauncher#47]
Would make handling more easy.

**Comment by jkuester** [comment]
I definitely see how this would eliminate an extra tap for users that primarily use the search box.  However, anyone who does not use the search box too much probably does not want the keyboard popping up every time they open the app drawer.  Maybe we could add an option to toggle the behavior....

Honestly, if we implement the change from https://github.com/jkuester/unlauncher/issues/43 to move the search box to the bottom, then it seems like the extra tap in the search box is probably not too troublesome since the user's hands would not have to move/stretch from the "typing position".

**Comment by AlbertoTrigo** [comment]
I find very suitable adding an option to toggle the keyboard automatically after sliding.
