### ISSUE TITLE
Follow device theme

### ISSUE THREAD

**Issue by Donkey-Doug** [jkuester/unlauncher#67]
Switch between light and dark theme depending on device settings.

**Comment by jkuester** [comment]
Related https://github.com/jkuester/unlauncher/issues/9

**Comment by hayribakici** [comment]
@jkuester I was wondering if it would be good practice to add a getter for an `UnlauncherDataSource` instance in the `MainActivity` since so far all the `UnlauncherDataSource` observers are done in the Fragments. The reason I am asking is, that I added another `proto` property `set_theme_wallpaper` for the `DrawerOptions` that enables the device background when the user has checked it (see screenshot)

<img src="https://user-images.githubusercontent.com/3295340/172057746-5814ae31-d460-4b96-a434-302230f5f2f3.png" height=300 />

With that the property `set_theme_wallpaper` gets set by the switch. Furthermore, I would like to observe this property in the `MainActivity` since the `MainActivity` is the place where the `Theme` gets set, too. You can see in the draft PR [here](https://github.com/jkuester/unlauncher/pull/112/files#diff-6efa0f858fe2ac060a8d040452c408339f3e732ac2a8f2b758883e819736a22fR106-R113) how the activity becomes aware of the theme change through `[setTheme()](https://github.com/jkuester/unlauncher/pull/112/files#diff-6efa0f858fe2ac060a8d040452c408339f3e732ac2a8f2b758883e819736a22fR144)` and sets the device wallpaper accordingly.
