### ISSUE TITLE
Forget scrolled position

### ISSUE THREAD

**Issue by Donkey-Doug** [jkuester/unlauncher#70]
Make it possible to forget the scrolled position in the app list.

**Comment by jkuester** [comment]
To clarify, are you referring to the following behavior?

- Swipe into the app drawer
- Scroll down
- Tap an app to open it
- Return to the home screen
- Swipe into the app drawer again
- (Instead of starting at the top of the app list, the app list starts from the last place you had scrolled to)

This is indeed a bug that needs to be fixed.

**Comment by Donkey-Doug** [comment]
Exactly.
