### ISSUE TITLE
Bug? When pressing the home button from an app, there is a 5-10 second delay to go to unlancher..

### ISSUE THREAD

**Issue by jlemonde** [jkuester/unlauncher#72]
Do you also experience this? It's very annoying as it feels very unresponsive.... 

I personally use Huawei Mate 20 Lite running Android 10.

**Comment by jlemonde** [comment]
PS: I'd potentially love to remove the transition when going back to home, too.

**Comment by jkuester** [comment]
Hmm, no, I do not get this kind of delay returning to home.  Are you running the latest version of Unlauncher from F-Droid? Also, can you think of anything in particular that might be specific to your setup?  Off the top of my head I am not sure what might be causing a performance problem like this....

**Comment by jlemonde** [comment]
Yes I am running the latest from F-Droid! 
The bug is not repeatable. Sometimes it happens, but shortly after using unlauncher, there is not delay any more. This lets me think that perhaps unlauncher was no longer cached / running in the background, so after some time, it needs some time to be started again...
Since Huawei has got some quite drastic power management, I even disabled the battery optimisations for unlauncher, but I believe that this doesn't change anything...

**Comment by jlemonde** [comment]
I notice that it is often much more than  1-2 seconds in fact. I get up to 10 second delays, which is completely abnormal.... Do you have an idea on why this could be? 

https://user-images.githubusercontent.com/30623792/126804315-4dcd0ce9-7768-4ef8-a310-1b16668fffd7.mp4

**Comment by jlemonde** [comment]
I am sad to tell you that I moved over to "Olauncher", another launcher with the same concept, and which does not feature this bug.

**Comment by xpthanos** [comment]
Hello! Dropping in to add my experience with this bug:

My smartphone model: **Xiaomi Redmi 7a**

### Before the "scroll to show app drawer" update

I was using Unlauncher for about a year, and I had noticed that whenever I pressed the "Apps" button on the bottom left to see my list of apps, the launcher was taking a bit of time to respond (2-3 seconds). I had assumed it was a feature rather a bug, in order to discourage using/looking at many apps (minimalism and stuff).

### After the update

The launcher has become unusable for me, since whenever I exit an application or unlock I have to wait about 3 seconds to be able to continue using my phone. I assume this is because Unlauncher has to populate this app list every time it's put in the foreground, as it's supposed to be immediately accessible by the user.

### Final note

Haven't looked at the code as I'm not familiar with android development, but for some reason populating the app list takes too long, at least in some devices (maybe less powerful ones?).

**Comment by jkuester** [comment]
@xpthanos thank you for your feedback on this too!  I am sorry to hear that you are experiencing these performance issues as well.  I agree with you that it must have something to do with populating the app list (since really the app does not much other I/O at all).  Unfortunately I have still not been able to reproduce this problem, even on devices with limited resources.  

However, as a part of #78 I have refactored the data model/flow for the app data that Unlauncher uses to populate the app drawer so that the list of apps should be cached. I am hoping this will eliminate the performance issue since the app will no longer be blocking to load the list of apps (but I cannot be sure since I have not recreated the issue).  These changes should be available on the next release (which should get published on F-Droid within the next week).

I will leave this issue open until I can get some confirmation that the performance problems have been resolved.
