### ISSUE TITLE
Missing apps in the app list

### ISSUE THREAD

**Issue by dealelopez** [jkuester/unlauncher#96]
Sometimes when I open the drawer some apps are missing.
I've found two different things: 
- Some random apps missing.
- Scroll finishes before ending the drawer.

I'm using version `1.3.0`. I haven't found this behavior in previous versions.

Android 11
Unlauncher version `1.3.0`

**Comment by jkuester** [comment]
Thanks for reporting this!  I have not heard of this behavior happening before in `1.3.0`.  Couple of follow-up questions to try to help pin-point the issue:

- Does this issue happen consistently (all/most of the time) or is it only rarely?
    - Does it only happen when apps are installed/uninstalled?
- Are the "random apps missing" the same apps all the time or do different apps show and then later disappear?  
- If you go to Options > Customize Drawer can you see all the apps (even the missing ones)?

**Comment by dealelopez** [comment]
Hi! thanks for thw support.

- This had happen four times since the launch of the v1.3.0. Nothing similar before.
    - No. This happen with random apps. Possible with apps that I have closed recently.
- First time I encounter this I didn't realized this was a "bug". I thought I uninstalled the app. Second time I started thinking maybe it was an unwanted behabior. They are different apps. For example, when found the problem, apps in the drawer finished in letter "T" not showing next letters.
    - When "Some apps missing" happens, "Scroll" problem also happened once, but no "Scroll" problem happened alone.
- If this happens again I'll check it.

**Comment by il2020** [comment]
I noticed that the list does not include the [OnlyOffice Documents application](https://play.google.com/store/apps/details?id=com.onlyoffice.documents), but 2 Music and Notes each :)

I use /e/OS v0.20-q (Android 10).

![Screenshot_20211227-183810_Unlauncher](https://user-images.githubusercontent.com/77854832/147511605-954ec8f8-2334-44cc-9ad8-3c008aca4e7a.png)

**Comment by jkuester** [comment]
I just wanted to add here that after more investigation and debugging, I am still not sure what could be causing this issue.

The list of apps, should get refreshed [each time the app resumes](https://github.com/jkuester/unlauncher/blob/4790fd30da0dd887e38c54b08ac2f2384d0ed4be/app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt#L93) and so if an app is missing it should always eventually get picked up.  What is most weird is that the actual logic for looking up the apps installed on the device did not change at all....

This has me thinking that something has to be going weird when Unlancher is trying to store data about the apps (a theory that would also "explain" the duplicate apps). But as of yet I have been unable to re-create the behavior (not to mention, my understanding of the Android Proto datastore is that it should be difficult to run into problems like this, but maybe something is implemented wrong...).  One thing I am pretty sure of is that the issue is not related to specific apps. Have tested both `ONLYOFFICE Docuements` and `Infinity` and both show up fine for me.
